### ISSUE TITLE
Earmuffs double ear storage capacity?

### ISSUE THREAD

**Issue by woothie** [HeavensGate/NSS-Eternal#18]
This is something I have not tried personally, and as such I don't have much to say about it. Reportedly, if you put on earmuffs and take them off, you can store two small items in one ear, as opposed to the normal procedure of storing one small item in your ear. More tests are needed to find the source of this.

**Comment by Moraak** [comment]
If the user means it shows two icons on your ear when wearing the earmuffs that is completley intentional. Aswell, you can place earmuffs overtop of one headset, and not use comms. I've been messing around with this and cant find the problem.

**Comment by Davnik** [comment]
If this hasn't been replicated by 12/1/14, remove the task. I don't really know the standard policy for that, but on 12/1/14, we'll go through and delete topics like this.
