### ISSUE TITLE
Deconstructable/constructable/non-static sinks?

### ISSUE THREAD

**Issue by woothie** [HeavensGate/NSS-Eternal#24]
Because plumming should totally be a thing. Really though, how about we make sinks less of an item that can't be moved or made elsewhere but where they're spawned, and more of an item people can remove if it's an inconvenience or they want it elsewhere? Just a thought, please do comment on this. Will put up for discussion on core eventually.

**Comment by Moraak** [comment]
Will put up for discussion on core eventually.

Bring it here once finalized.
