### ISSUE TITLE
Irremovable bushes

### ISSUE THREAD

**Issue by woothie** [HeavensGate/NSS-Eternal#25]
More or less self-explainatory, leafy organic bushes made out of plant stuff shouldn't be something that can't be weeded away or removed by the ordinary player, for better or for worse. Also make it possible to make bushes somehow, I guess. Random spawn on newly planted grass tiles? Idk. Will put up for discussion on core eventually.

**Comment by Moraak** [comment]
Idk. Will put up for discussion on core eventually.

Don't post here untill its officially decided or I might add it by mistake.

**Comment by Davnik** [comment]
I support this, and figure the results should be achievable with a spade, hatchet or wirecutters. More items can be added to this list. In theory, anything with edge should be able to hack away at it slowly. Not sure how we want to implement adding bushes though. Maybe "bush seeds" in the Servitor, which grow into a harvestable bush, which can be picked up and placed on grass tiles by using the item.

**Comment by Moraak** [comment]
As stated before don't post here untill its been decided on.
