### ISSUE TITLE
MotD popup on join

### ISSUE THREAD

**Issue by woothie** [HeavensGate/NSS-Eternal#28]
Pretty self-explainatory. We want to have a popup on join, showing the MotD, containing links to useful resources, the rules and most importanly, the character briefing. It's been considered taht this popup be make into a briefing popup, but this has yet to be discussed properly. In any case, we want a popup on join! As of right now, we don't know exacly what to put in it, so just make the framework or put in what's already in the MotD.

**Comment by Moraak** [comment]
Already told someone I need the html for it.

**Comment by woothie** [comment]
It should be in- oh yeah, you don't have SSH access... I'll get you that file.

**Comment by staticcharged** [comment]
will this be just a white box with text or can we use a nano UI for this to make it attractive and immersive?

**Comment by Davnik** [comment]
Discuss this with Jakk - it's his textbox. However, we would like to know how easy or hard or laggy or restricted it is to set up a NanoUI interface/dialog box.

**Comment by Moraak** [comment]
We cant know how laggy it would be first of all, unless it was tested and ran. Second of all this is the wrong repo.
