### ISSUE TITLE
AI saycodes

### ISSUE THREAD

**Issue by woothie** [HeavensGate/NSS-Eternal#33]
Such as :e and :s to talk on engineering and security, rather than having to rely on intercomms.

**Comment by berkbuzcu** [comment]
Easy peasy.

**Comment by Davnik** [comment]
This is already in the latest version of BS12, and as such can be amalgamated into that priority. Note that the AI cannot use ERT or Special Ops channels, but has access to the ERT frequency on its intercomms.

**Comment by Davnik** [comment]
(Requesting this issue be closed. This will be resolved on migration to BS12.)
