### ISSUE TITLE
Round-end alteration

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/NSS-Eternal#35]
This will be a bit of an undertaking and require both coding and mapping work.

We want to alter the end-of-round events. A few things will need to happen.

1) The shuttle will travel for 3 minutes.
2) The shuttle will arrive in empty space, make a CentComm Command Report that the engines appear to have malfunctioned, and a repair shuttle should arrive soon.
3) Two minutes will pass, and then the server will restart. 

The subtle implication is that one never truly escapes The Gate, and a pseudo-groundhog day event happens, pulling you into the next shift ambiguously.

We want this to be truly empty space - it was mentioned that we could put it in a z-level that's already in use, but even if people find some means of exploring local space, they shouldn't be able to find anything. I was thinking a simple z-level  with nothing but space tiles and the shuttle.

**Comment by Moraak** [comment]
Wrong repo to post on.
