### ISSUE TITLE
Timers Redux

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/NSS-Eternal#37]
The timer should be improved to a complete Space Law Panel. It would have a number of features, but effectively streamline the process. Among the projected features are as follows.
~Time should be customizable in a simpler format than adding one minute repeatedly. Custom sentences should be allowed, for case-by-case guesstimation work, knowing the circumstances with this particular individual.
~Crimes should be listed next to their recommended and maximum sentences, in table format, without lengthy descriptions (unless we can hyperlink the name of the crime to a popup pasted from the BS12 wiki.) If it's simple to do, crimes should be color coded: minor -> yellow, medium -> orange, high -> red. 
~Clicking on the recommended time, or a checkbox in a "recommended time" column (next to a "maximum sentence" column/checkbox) will add that sentence to the tracker. 
~Below the list of crimes should be a separate area with two columns, "Situation" and "Notes" - Surrender (-25%), Cooperation (-25%, or 50% revealing a head revolutionary), Self Defense (up to immediate release), Re-education (up to immediate release), and for documentation Medical Intervention. Those with reduction values should follow the same procedure as adding minutes, either via link on the text or checkbox.
~The logic used to figure the time should use no less than the recommended sentence of the highest crime (in minutes), and add minutes from the remaining crimes based upon some other logic I can't really think of. Maybe 5 or 10 minutes per additional crime. Furthermore, the percentage reduction should apply after all other calculations. 10+5/2 = (10+5)/2, not 10/2 + 5. :p
~Once the sentence has been carried out, the timer should announce all sentences served and due: "[X] minutes served. Recommended procedures: [compulsary psychological evaluation, tracking implant, report to Sol Government.]" This will essentially pull all non-time values from the checked boxes and announce them so security remembers to do them all, and the prisoner is notified of his expected sentencing. Optionally, this can be presented before _and_ after the sentence, so security sees to anything necessary in the process and doesn't miss the final announcement.

**Comment by Davnik** [comment]
If possible, use the sleek black and blue of NanoUI to present this masterpiece.

**Comment by staticcharged** [comment]
I really look forward to seeing this :3

**Comment by Moraak** [comment]
Unfortunately I cant do anything untill Woothie gives me full access of the Latest Eternal repository. Also this is the wrong repo to post on.
